export interface AllahName {
  id: number
  arabic: string
  transliteration: string
  meaningBn: string
  meaningEn: string
}

export const ALLAH_NAMES: AllahName[] = [
  { id: 1, arabic: "اللَّهُ", transliteration: "Allah", meaningBn: "একমাত্র সত্য উপাস্য", meaningEn: "The Only True God" },
  { id: 2, arabic: "الرَّحْمَنُ", transliteration: "Ar-Rahman", meaningBn: "পরম দয়ালু", meaningEn: "The Most Gracious" },
  { id: 3, arabic: "الرَّحِيمُ", transliteration: "Ar-Rahim", meaningBn: "অতিশয় মেহেরবান", meaningEn: "The Most Merciful" },
  { id: 4, arabic: "الْمَلِكُ", transliteration: "Al-Malik", meaningBn: "সর্বভৌম ক্ষমতার অধিকারী", meaningEn: "The Absolute Ruler" },
  { id: 5, arabic: "الْقُدُّوسُ", transliteration: "Al-Quddus", meaningBn: "অতি পবিত্র", meaningEn: "The Most Holy" },
  { id: 6, arabic: "السَّلَامُ", transliteration: "As-Salam", meaningBn: "শান্তি ও নিরাপত্তা দানকারী", meaningEn: "The Source of Peace" },
  { id: 7, arabic: "الْمُؤْمِنُ", transliteration: "Al-Mu'min", meaningBn: "নিরাপত্তা ও ঈমান দানকারী", meaningEn: "The Giver of Security" },
  { id: 8, arabic: "الْمُهَيْمِنُ", transliteration: "Al-Muhaymin", meaningBn: "রক্ষণাবেক্ষণকারী", meaningEn: "The Guardian" },
  { id: 9, arabic: "الْعَزِيزُ", transliteration: "Al-Aziz", meaningBn: "পরাক্রমশালী", meaningEn: "The All-Mighty" },
  { id: 10, arabic: "الْجَبَّارُ", transliteration: "Al-Jabbar", meaningBn: "মহাপ্রতাপশালী", meaningEn: "The Compeller" },
  { id: 11, arabic: "الْمُتَكَبِّرُ", transliteration: "Al-Mutakabbir", meaningBn: "মহা গৌরবান্বিত", meaningEn: "The Supreme" },
  { id: 12, arabic: "الْخَالِقُ", transliteration: "Al-Khaliq", meaningBn: "সৃষ্টিকর্তা", meaningEn: "The Creator" },
  { id: 13, arabic: "الْبَارِئُ", transliteration: "Al-Bari'", meaningBn: "উদ্ভাবক", meaningEn: "The Originator" },
  { id: 14, arabic: "الْمُصَوِّرُ", transliteration: "Al-Musawwir", meaningBn: "রূপদানকারী", meaningEn: "The Fashioner" },
  { id: 15, arabic: "الْغَفَّارُ", transliteration: "Al-Ghaffar", meaningBn: "পরম ক্ষমাশীল", meaningEn: "The All-Forgiving" },
  { id: 16, arabic: "الْقَهَّارُ", transliteration: "Al-Qahhar", meaningBn: "দমনকারী", meaningEn: "The Subduer" },
  { id: 17, arabic: "الْوَهَّابُ", transliteration: "Al-Wahhab", meaningBn: "মহান দাতা", meaningEn: "The Bestower" },
  { id: 18, arabic: "الرَّزَّاقُ", transliteration: "Ar-Razzaq", meaningBn: "রিযিকদাতা", meaningEn: "The Provider" },
  { id: 19, arabic: "الْفَتَّاحُ", transliteration: "Al-Fattah", meaningBn: "বিজয়দানকারী", meaningEn: "The Opener" },
  { id: 20, arabic: "الْعَلِيمُ", transliteration: "Al-Alim", meaningBn: "সর্বজ্ঞ", meaningEn: "The All-Knowing" },
  { id: 21, arabic: "الْقَابِضُ", transliteration: "Al-Qabid", meaningBn: "সংকীর্ণকারী", meaningEn: "The Restrainer" },
  { id: 22, arabic: "الْبَاسِطُ", transliteration: "Al-Basit", meaningBn: "প্রশস্তকারী", meaningEn: "The Expander" },
  { id: 23, arabic: "الْخَافِضُ", transliteration: "Al-Khafid", meaningBn: "অবনতকারী", meaningEn: "The Abaser" },
  { id: 24, arabic: "الرَّافِعُ", transliteration: "Ar-Rafi'", meaningBn: "উন্নতকারী", meaningEn: "The Exalter" },
  { id: 25, arabic: "الْمُعِزُّ", transliteration: "Al-Mu'izz", meaningBn: "সম্মান দানকারী", meaningEn: "The Giver of Honour" },
  { id: 26, arabic: "الْمُذِلُّ", transliteration: "Al-Muzill", meaningBn: "অপমানকারী", meaningEn: "The Dishonourer" },
  { id: 27, arabic: "السَّمِيعُ", transliteration: "As-Sami'", meaningBn: "সর্বশ্রোতা", meaningEn: "The All-Hearing" },
  { id: 28, arabic: "الْبَصِيرُ", transliteration: "Al-Basir", meaningBn: "সর্বদ্রষ্টা", meaningEn: "The All-Seeing" },
  { id: 29, arabic: "الْحَكَمُ", transliteration: "Al-Hakam", meaningBn: "বিচারক", meaningEn: "The Judge" },
  { id: 30, arabic: "الْعَدْلُ", transliteration: "Al-Adl", meaningBn: "পরিপূর্ণ ন্যায়বিচারক", meaningEn: "The Just" },
  { id: 31, arabic: "اللَّطِيفُ", transliteration: "Al-Latif", meaningBn: "সূক্ষ্মদর্শী", meaningEn: "The Subtle One" },
  { id: 32, arabic: "الْخَبِيرُ", transliteration: "Al-Khabir", meaningBn: "সম্যক অবগত", meaningEn: "The All-Aware" },
  { id: 33, arabic: "الْحَلِيمُ", transliteration: "Al-Halim", meaningBn: "অত্যন্ত ধৈর্য্যশীল", meaningEn: "The Forbearing" },
  { id: 34, arabic: "الْعَظِيمُ", transliteration: "Al-Azim", meaningBn: "সুমহান", meaningEn: "The Magnificent" },
  { id: 35, arabic: "الْغَفُورُ", transliteration: "Al-Ghafur", meaningBn: "পরম ক্ষমাশীল", meaningEn: "The All-Forgiving" },
  { id: 36, arabic: "الشَّكُورُ", transliteration: "Ash-Shakur", meaningBn: "পুরস্কারদাতা", meaningEn: "The Appreciative" },
  { id: 37, arabic: "الْعَلِيُّ", transliteration: "Al-Ali", meaningBn: "সুউচ্চ", meaningEn: "The Most High" },
  { id: 38, arabic: "الكَبِيرُ", transliteration: "Al-Kabir", meaningBn: "সর্বশ্রেষ্ঠ", meaningEn: "The Most Great" },
  { id: 39, arabic: "الْحَفِيظُ", transliteration: "Al-Hafiz", meaningBn: "হেফাজতকারী", meaningEn: "The Preserver" },
  { id: 40, arabic: "المُقِيتُ", transliteration: "Al-Muqit", meaningBn: "খাদ্যদাতা", meaningEn: "The Maintainer" },
  { id: 41, arabic: "الحَسِيبُ", transliteration: "Al-Hasib", meaningBn: "হিসাব গ্রহণকারী", meaningEn: "The Reckoner" },
  { id: 42, arabic: "الجَلِيلُ", transliteration: "Al-Jalil", meaningBn: "মর্যাদাবান", meaningEn: "The Majestic" },
  { id: 43, arabic: "الكَرِيمُ", transliteration: "Al-Karim", meaningBn: "উদার", meaningEn: "The Generous" },
  { id: 44, arabic: "الرَّقِيبُ", transliteration: "Ar-Raqib", meaningBn: "পর্যবেক্ষক", meaningEn: "The Watchful" },
  { id: 45, arabic: "المُجِيبُ", transliteration: "Al-Mujib", meaningBn: "প্রার্থনা কবুলকারী", meaningEn: "The Responder" },
  { id: 46, arabic: "الوَاسِعُ", transliteration: "Al-Wasi'", meaningBn: "অসীম", meaningEn: "The All-Encompassing" },
  { id: 47, arabic: "الحَكِيمُ", transliteration: "Al-Hakim", meaningBn: "মহাপ্রাজ্ঞ", meaningEn: "The All-Wise" },
  { id: 48, arabic: "الوَدُودُ", transliteration: "Al-Wadud", meaningBn: "প্রেমময়", meaningEn: "The Loving" },
  { id: 49, arabic: "المَجِيدُ", transliteration: "Al-Majid", meaningBn: "সম্মানিত", meaningEn: "The Glorious" },
  { id: 50, arabic: "البَاعِثُ", transliteration: "Al-Ba'ith", meaningBn: "পুনরুত্থানকারী", meaningEn: "The Resurrector" },
  { id: 51, arabic: "الشَّهِيدُ", transliteration: "Ash-Shahid", meaningBn: "সাক্ষী", meaningEn: "The Witness" },
  { id: 52, arabic: "الحَقُّ", transliteration: "Al-Haqq", meaningBn: "পরম সত্য", meaningEn: "The Absolute Truth" },
  { id: 53, arabic: "الوَكِيلُ", transliteration: "Al-Wakil", meaningBn: "ভীষণ নির্ভরযোগ্য", meaningEn: "The Trustee" },
  { id: 54, arabic: "القَوِيُّ", transliteration: "Al-Qawi", meaningBn: "শক্তিমান", meaningEn: "The All-Strong" },
  { id: 55, arabic: "المَتِينُ", transliteration: "Al-Matin", meaningBn: "অটল", meaningEn: "The Firm" },
  { id: 56, arabic: "الوَلِيُّ", transliteration: "Al-Wali", meaningBn: "অভিভাবক", meaningEn: "The Protecting Friend" },
  { id: 57, arabic: "الحَمِيدُ", transliteration: "Al-Hamid", meaningBn: "প্রশংসিত", meaningEn: "The Praiseworthy" },
  { id: 58, arabic: "المُحْصِي", transliteration: "Al-Muhsi", meaningBn: "হিসাবকারী", meaningEn: "The Accounter" },
  { id: 59, arabic: "المُبْدِئُ", transliteration: "Al-Mubdi'", meaningBn: "উদ্ভাবক", meaningEn: "The Originator" },
  { id: 60, arabic: "المُعِيدُ", transliteration: "Al-Mu'id", meaningBn: "পুনরায় সৃষ্টিকর্তা", meaningEn: "The Restorer" },
  { id: 61, arabic: "المُحْيِي", transliteration: "Al-Muhyi", meaningBn: "জীবন দানকারী", meaningEn: "The Giver of Life" },
  { id: 62, arabic: "المُمِيتُ", transliteration: "Al-Mumit", meaningBn: "মৃত্যু দানকারী", meaningEn: "The Bringer of Death" },
  { id: 63, arabic: "الحَيُّ", transliteration: "Al-Hayy", meaningBn: "চিরঞ্জীব", meaningEn: "The Ever-Living" },
  { id: 64, arabic: "القَيُّومُ", transliteration: "Al-Qayyum", meaningBn: "সবকিছুর ধারক", meaningEn: "The Self-Subsisting" },
  { id: 65, arabic: "الوَاجِدُ", transliteration: "Al-Wajid", meaningBn: "অফুরন্ত ভাণ্ডারের অধিকারী", meaningEn: "The Finder" },
  { id: 66, arabic: "المَاجِدُ", transliteration: "Al-Majid", meaningBn: "মহিমাময়", meaningEn: "The Noble" },
  { id: 67, arabic: "الوَاحِدُ", transliteration: "Al-Wahid", meaningBn: "এক ও অদ্বিতীয়", meaningEn: "The Unique" },
  { id: 68, arabic: "الأَحَدُ", transliteration: "Al-Ahad", meaningBn: "এক", meaningEn: "The One" },
  { id: 69, arabic: "الصَّمَدُ", transliteration: "As-Samad", meaningBn: "অমুখাপেক্ষী", meaningEn: "The Eternal" },
  { id: 70, arabic: "القَادِرُ", transliteration: "Al-Qadir", meaningBn: "ক্ষমতাবান", meaningEn: "The All-Powerful" },
  { id: 71, arabic: "المُقْتَدِرُ", transliteration: "Al-Muqtadir", meaningBn: "সিদ্ধান্তের অধিকারী", meaningEn: "The All-Determining" },
  { id: 72, arabic: "المُقَدِّمُ", transliteration: "Al-Muqaddim", meaningBn: "অগ্রবতীকারী", meaningEn: "The Expediter" },
  { id: 73, arabic: "المُؤَخِّرُ", transliteration: "Al-Mu'akhkhir", meaningBn: "বিলম্বকারী", meaningEn: "The Delayer" },
  { id: 74, arabic: "الأَوَّلُ", transliteration: "Al-Awwal", meaningBn: "প্রথম", meaningEn: "The First" },
  { id: 75, arabic: "الآخِرُ", transliteration: "Al-Akhir", meaningBn: "শেষ", meaningEn: "The Last" },
  { id: 76, arabic: "الظَّاهِرُ", transliteration: "Az-Zahir", meaningBn: "প্রকাশ্য", meaningEn: "The Manifest" },
  { id: 77, arabic: "البَاطِنُ", transliteration: "Al-Batin", meaningBn: "গোপন", meaningEn: "The Hidden" },
  { id: 78, arabic: "الوَالِي", transliteration: "Al-Wali", meaningBn: "শাসক", meaningEn: "The Governing One" },
  { id: 79, arabic: "المُتَعَالِي", transliteration: "Al-Muta'ali", meaningBn: "সুউচ্চ", meaningEn: "The Most Exalted" },
  { id: 80, arabic: "البَرُّ", transliteration: "Al-Barr", meaningBn: "সদাচারী", meaningEn: "The Good" },
  { id: 81, arabic: "التَّوَّابُ", transliteration: "At-Tawwab", meaningBn: "তওবা কবুলকারী", meaningEn: "The Acceptor of Repentance" },
  { id: 82, arabic: "المُنْتَقِمُ", transliteration: "Al-Muntaqim", meaningBn: "প্রতিশোধ গ্রহণকারী", meaningEn: "The Avenger" },
  { id: 83, arabic: "العَفُوُّ", transliteration: "Al-Afuww", meaningBn: "ক্ষমাশীল", meaningEn: "The Pardoner" },
  { id: 84, arabic: "الرَّؤُوفُ", transliteration: "Ar-Ra'uf", meaningBn: "স্নেহশীল", meaningEn: "The Kind" },
  { id: 85, arabic: "مَالِكُ المُلْكِ", transliteration: "Malik-ul-Mulk", meaningBn: "সার্বভৌম ক্ষমতার অধিকারী", meaningEn: "The Owner of All Sovereignty" },
  { id: 86, arabic: "ذُو الجَلالِ وَالإِكْرَامِ", transliteration: "Dhul-Jalali Wal-Ikram", meaningBn: "সম্মানের অধিকারী", meaningEn: "The Lord of Majesty and Honour" },
  { id: 87, arabic: "المُقْسِطُ", transliteration: "Al-Muqsit", meaningBn: "ন্যায়পরায়ণ", meaningEn: "The Equitable One" },
  { id: 88, arabic: "الجَامِعُ", transliteration: "Al-Jami'", meaningBn: "একত্রকারী", meaningEn: "The Gatherer" },
  { id: 89, arabic: "الغَنِيُّ", transliteration: "Al-Ghani", meaningBn: "অভাবমুক্ত", meaningEn: "The Rich One" },
  { id: 90, arabic: "المُغْنِي", transliteration: "Al-Mughni", meaningBn: "ঐশ্বর্যদানকারী", meaningEn: "The Enricher" },
  { id: 91, arabic: "المَانِعُ", transliteration: "Al-Mani'", meaningBn: "প্রতিরোধকারী", meaningEn: "The Preventer of Harm" },
  { id: 92, arabic: "الضَّارُّ", transliteration: "Ad-Darr", meaningBn: "ক্ষতি সাধনকারী", meaningEn: "The Creator of Harmful" },
  { id: 93, arabic: "النَّافِعُ", transliteration: "An-Nafi'", meaningBn: "কল্যাণ সাধনকারী", meaningEn: "The Creator of Good" },
  { id: 94, arabic: "النُّورُ", transliteration: "An-Nur", meaningBn: "আলো", meaningEn: "The Light" },
  { id: 95, arabic: "الهَادِي", transliteration: "Al-Hadi", meaningBn: "পথপ্রদর্শক", meaningEn: "The Guide" },
  { id: 96, arabic: "البَدِيعُ", transliteration: "Al-Badi'", meaningBn: "অতুলনীয় সৃষ্টিকর্তা", meaningEn: "The Originator" },
  { id: 97, arabic: "البَاقِي", transliteration: "Al-Baqi", meaningBn: "চিরস্থায়ী", meaningEn: "The Everlasting One" },
  { id: 98, arabic: "الوَارِثُ", transliteration: "Al-Warith", meaningBn: "উত্তরাধিকারী", meaningEn: "The Inheritor of All" },
  { id: 99, arabic: "الرَّشِيدُ", transliteration: "Ar-Rashid", meaningBn: "সঠিক পথপ্রদর্শক", meaningEn: "The Righteous Teacher" },
  { id: 100, arabic: "الصَّبُورُ", transliteration: "As-Sabur", meaningBn: "অত্যন্ত ধৈর্য্যশীল", meaningEn: "The Patient One" },
]
